-- AlterTable
ALTER TABLE `notifications` MODIFY `eventType` ENUM('PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_DELETED', 'PRODUCT_PUBLISHED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED') NOT NULL;
